### ISSUE TITLE
关于 Linux 硬链接和软链接有什么区别 的问题

### ISSUE THREAD

**Issue by BruceZhang1993** [todayqq/PHPerInterviewGuide#1]
第三点
无论删除 软链接 或是 硬链接，对源文件都没有任何影响（未删除可访问）～

PS.
删除源文件，会导致软链接失效，硬链接无影响～

**Comment by by2009** [comment]
>3. 删除硬链接文件，不会删除原文件，删除软链接文件，会把原文件删除

删除软链接并不影响被指向的文件，但若被指向的原文件被删除，则相关软连接被称为死链接（即 dangling link，若被指向路径文件被重新创建，死链接可恢复为正常的软链接）

**Comment by todayqq** [comment]
@by2009 @BruceZhang1993 

感谢指正，已修改

**Comment by BruceZhang1993** [comment]
Resolved.
