### ISSUE TITLE
快排算法问题

### ISSUE THREAD

**Issue by azerothyang** [todayqq/PHPerInterviewGuide#4]
快排算法有种的一个问题, 例如:
$arr = [2,3,2,6,7,1];
当basenum 为2,  而循环体内
foreach ($arr as $v) {
        if ($baseNum > $v) {
            $leftArr[] = $v;
        }
        if ($baseNum < $v) {
            $rightArr[] = $v;
        }
}
当$baseNum=$v时, $v的值会被丢失,不在left,right数组中, 可以通过加入等于的判断条件
$count = count($arr);
    for ($i=1; $i<$count; $i++){
        if($arr[$i] <= $basic){
            $left[] = $arr[$i];
        }
        else{
            $right[] = $arr[$i];
        }
    }
就能在排序后的数组中包含相等的数了。

**Comment by todayqq** [comment]
@azerothyang 

这个快速排序算法有问题，没有考虑元素相同的情况，现已修改
